name: Cypress Tests

on:
  pull_request:
    branches:
      - main  # Substitua pela branch alvo das pull requests
  push:
    branches:
      - main  # Substitua pela branch alvo dos pushes
  workflow_dispatch:  # Evento para execução manual

jobs:
  cypress_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Use a versão do Node.js compatível com o projeto

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run cypress:run  # Substitua pelo comando correto para executar seus testes Cypress

      # Agendamento para executar às 8 horas e 17 horas todos os dias
      - name: Execute at specific times
        run: |
          if [ "$(date '+%H')" -eq "8" ] || [ "$(date '+%H')" -eq "17" ]; then
            npm run cypress:run
          else
            echo "Skipping tests at this time."
          fi
